# Generated by Django 4.2.5 on 2023-09-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="repo_name",
            field=models.CharField(default="Repo must be named", max_length=255),
        ),
        migrations.AddField(
            model_name="repo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
