# Generated by Django 4.2.5 on 2023-09-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0002_repo_repo_name_repo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="repo_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="repo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
