# Generated by Django 4.2.5 on 2023-09-27 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0004_repoaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="box_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="box",
            name="box_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="box",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="box",
            name="repo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="box.repo"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="box",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
